services:
  - type: web
    name: transferx-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: transferx-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://transferx-backend.onrender.com
